
storm_data$EVTYPE <- gsub(".*TORNADO.*", "TORNADO", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*MISHAP.*", "OTHER", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*MARINE THUNDER.*", "MRNTST", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*MARINE TSTM.*", "MRNTST", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*NON.*TSTM.*", "STRONG WIND", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*THUND.* | .*TSTM.*", "THUNDERSTORM WIND", storm_data$EVTYPE)

storm_data$EVTYPE <- gsub(".*TSTM.*", "THUNDERSTORM WIND", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*AVALA.*", "AVALANCHE", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*LIGHTN.*", "LIGHTNING", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*FLASH.*", "FLSFLD", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*COASTAL.*", "CSTFLD", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*BEACH FLO.*", "CSTFLD", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*CSTL.*", "CSTFLD", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*FLOOD.*", "FLOOD", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*WINTRY.*", "WINTERY", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*WINTER WEATH.*", "WINTERY", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*WINTER MIX.*", "WINTERY", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*WINTERY MIX.*", "WINTERY", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*RECORD WINTER.*", "WINTERY", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*WINTER STORM.*", "WINTER STORM", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*HURR.*", "HURRICANE", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*TYPHOON.*", "HURRICANE", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*SNOW.*", "HEAVY SNOW", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*TROPICAL STO.*", "TROPICAL STORM", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*TROPICAL DEP.*", "TROPICAL DEPRESSION", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*FIRE.*", "WILDFIRE", storm_data$EVTYPE)
storm_data$EVTYPE <- gsub(".*DENSE FOG.*", "DNSFG", storm_data$EVTYPE)
